### ISSUE TITLE
pi hängt sich random auf

### ISSUE THREAD

**Issue by TPausL** [ProjektDevLights/Server#16]
habe das gefühl, dass der pi bei zu vielen anfragen kein bock mehr hat. ganz komische sache. hängt sich dann irgendtwie komplett auf.

**Comment by TPausL** [comment]
habe ich nicht mehr festgestellt war glaube ich der errconreset

@Jozys wenn das bei dir der fall war mach das hier wieder auf

**Comment by Jozys** [comment]
Ist bei mir noch kein einziges Mal aufgetreten. Kann also erstmal geschlossen bleiben. 
Sollte es doch mal auftreten öffne ich das wieder.

**Comment by TPausL** [comment]
perfekt
