### ISSUE TITLE
sleep timer for lights

### ISSUE THREAD

**Issue by Jozys** [ProjektDevLights/Server#97]
Vielleicht ein Sleep Timer für die Lichter. 
Dass das Licht nach einer bestimmten Zeit ausgeht?

**Comment by Jozys** [comment]
ist jetzt erstmal implementiert über cron jobs für einzelne lichter.
Weiß nicht ob man das auch für tags machen sollte.

**Comment by TPausL** [comment]
ja

**Comment by TPausL** [comment]
ist das nicht fertig?

**Comment by Jozys** [comment]
Jo eigentlich schon
